src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $theme = null;

    #[ORM\Column(length: 50)]
    private ?string $category = null;

    #[ORM\Column(length: 50)]
    private ?string $language = null;

    #[ORM\Column]
    #[Assert\PositiveOrZero(message: "La quantité doit être un nombre positif ou nul.")]
    private ?int $quantity = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Author $author = null;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: Reservation::class)]
    private Collection $reservations;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\OneToOne(mappedBy: 'book', cascade: ['persist', 'remove'])]
    private ?BookAvailability $availability = null;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: Review::class)]
    private Collection $reviews;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): static
    {
        $this->theme = $theme;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): static
    {
        $this->language = $language;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setBook($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getBook() === $this) {
                $reservation->setBook(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }

    public function getAvailability(): ?BookAvailability
    {
        return $this->availability;
    }

    public function setAvailability(?BookAvailability $availability): static
    {
        // unset the owning side of the relation if necessary
        if ($availability === null && $this->availability !== null) {
            $this->availability->setBook(null);
        }

        // set the owning side of the relation if necessary
        if ($availability !== null && $availability->getBook() !== $this) {
            $availability->setBook($this);
        }

        $this->availability = $availability;

        return $this;
    }

    public function isAvailable(): bool
    {
        return $this->quantity > 0;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setBook($this);
        }
        return $this;
    }

    public function removeReview(Review $review): static
    {
        if ($this->reviews->removeElement($review)) {
            if ($review->getBook() === $this) {
                $review->setBook(null);
            }
        }
        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\Rental;
use App\Form\FilterBooksType;
use App\Form\RentBookType;
use App\Form\ReviewType;
use App\Message\RentBook;
use App\Service\EdifactService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_index')]
    public function index(): Response
    {

        return $this->render('frontend/main/index.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }

    /**
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    #[Route('/catalog/browse', name: 'app_catalog_browse')]
    public function catalog(
        EntityManagerInterface $entityManager,
        Request $request
    ): Response
    {
        $form = $this->createForm(FilterBooksType::class, [], [
            'action' => $this->generateUrl('app_catalog_browse'),
            'method' => 'GET',
        ]);
        $form->handleRequest($request);
        $catalog = $entityManager->getRepository(Book::class)->findAll();

        if ($form->isSubmitted()) {
            $searchPattern = $form->getData()['searchPattern'];
            $catalog = $entityManager->getRepository(Book::class)->findByAuthorOrTitle($searchPattern);

            return $this->render('frontend/main/catalog/browse.html.twig', [
                'catalog' => $catalog,
                'form' => $form->createView()
            ]);
        }

        return $this->render('frontend/main/catalog/browse.html.twig', [
            'catalog' => $catalog,
            'form' => $form->createView()
        ]);
    }

    #[Route('/catalog/rent', name: 'app_catalog_rent')]
    public function catalogRent(
        Request $request,
        MessageBusInterface $bus,
        EdifactService $edifactService
    ): Response
    {
        $form = $this->createForm(RentBookType::class);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            /** @var Rental $rental */
            $rental = $form->getData();
            $user = $this->getUser();
            if (!$user) {
                throw $this->createAccessDeniedException('Vous devez être connecté pour emprunter un livre.');
            }

            $message = $edifactService->generateEDIFACTRentMessage(
                $rental->getRentFrom()?->format('Ymd'),
                $rental->getRentTo()?->format('Ymd'), 
                $user->getUserIdentifier(),
                $rental->getBook()?->getId()
            );

            // Publikacja wiadomości na kolejce
            $bus->dispatch(new RentBook($message));

            $this->addFlash('success', 'Excellent! La location a été effectuée avec succès, vous pouvez la visualiser sur la page de location');
            return $this->redirectToRoute('app_rents', []);

        }

        return $this->render('frontend/main/catalog/rent.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/book/{id}/details', name: 'app_book_details')]
    public function bookDetails(
        Book $book,
        Request $request,
        EntityManagerInterface $entityManager
    ): Response
    {
        $form = $this->createForm(ReviewType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $review = $form->getData();
            $review->setBook($book);
            $review->setCreatedAt(new \DateTimeImmutable());

            $entityManager->persist($review);
            $entityManager->flush();

            return $this->redirectToRoute('app_book_details', ['id' => $book->getId()]);
        }
        return $this->render('frontend/main/book/details.html.twig', [
            'book' => $book,
            'form' => $form->createView()
        ]);
    }

    #[Route('/rents', name: 'app_rents')]
    public function rents(
    ): Response
    {

        return $this->render('frontend/main/rent/index.html.twig', [

        ]);
    }

    #[Route('/rents/{id}/return', name: 'app_book_return')]
    public function return(
        Rental $rental,
        EntityManagerInterface $entityManager
    ): Response
    {

        $rental->setReturned(true);
        $entityManager->persist($rental);

        $bookAvailable = $rental->getBook()->getAvailability();

        $bookAvailable->setAvailable($bookAvailable->getAvailable() + 1);
        $entityManager->persist($bookAvailable);

        $entityManager->flush();

        $this->addFlash('success', 'Merci d\'avoir rendu le livre !');
        return $this->redirectToRoute('app_rents', []);
    }
}

templates/frontend/main/catalog/browse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue{% endblock %}

{% block body %}
<div class="row g-5">
    <div class="col-md-12">
        <h2>Articles disponibles</h2>

        {{ form_start(form) }}
        <div class="row">
            <div class="col-sm-12 col-md-6">
                {{ form_row(form.searchPattern, {
                    'label': 'Entrez un auteur, thème ou un titre'
                }) }}
            </div>
            <div class="col-12">
                <div class="activity__form__submit">
                    {{ form_row(form.submit, {
                        'label': 'Rechercher'
                    }) }}
                </div>
            </div>
        </div>
        {{ form_end(form) }}

        <table class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Auteur</th>
                    <th scope="col">Thème</th>
                    <th scope="col">Disponibilité</th>
                    <th scope="col">Avis</th>
                </tr>
            </thead>
            <tbody>
                {% for position in catalog %}
                    <tr>
                        <td>{{ position.id }}</td>
                        <td>{{ position.name }}</td>
                        <td>
                            {% for author in position.author %}
                                {{ author.name }}
                            {% endfor %}
                        </td>
                        <td>{{ position.theme }}</td>
                        <td>{{ position.availability.available }} / {{ position.availability.total }}</td>
                        <td>
                            <a class="btn btn-light" href="{{ path('app_book_details', {id: position.id}) }}">Détails</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/frontend/main/catalog/rent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunter un livre{% endblock %}

{% block body %}
    <div class="row g-5">
        <div class="col-md-6">
            <h2>Formulaire de prêt</h2>
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% if app.user %}
                {{ form_start(form) }}

                {{ form_row(form.itemId, {
                    label: 'Choisissez un livre'
                }) }}
                {{ form_row(form.rentFrom, {
                    label: 'Début du prêt'
                }) }}
                {{ form_row(form.rentTo, {
                    label: 'Fin du prêt'
                }) }}
                {{ form_row(form.submit, {
                    label: 'Louer'
                }) }}
                {{ form_end(form) }}
            {% else %}
                <div class="alert alert-danger">
                    <p>
                        Vous devez être connecté pour emprunter un livre
                    </p>
                    <p>
                        <a class="btn btn-primary" href="{{ path('app_login') }}">Se connecter</a>
                    </p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}